### ISSUE TITLE
possible patches needed:

### ISSUE THREAD

**Issue by Martianganja** [Wild-W/CivilizationVI_CommunityExtension#3]
"AB2531" Plague Mod" by NHC and FearSunn,
"SpatialX Plague mod Rework"" by SpatialX,
"AB2531 Buy Units with Faith" by NHC,
"Trainable Religious Units" by ChessPro2007,
"Late-Game Religion [EXPERIMENTAL MOD]" by Boa of the Boaians (ᜊᜓᜀ),
"Foreign Resource Extraction 3.0" by Liam
"Wildlife" by Shirotora Kenshin and Deliverator23,
"【Immigration】Move your population" by WindFly,
"Cultural Invasion and Immigration" by sleeping_fish,
"Enhanced Goodies and Hostile Villagers" by yofabronecoforo,
"Enhanced Community FrontEnd" by yofabronecoforo,
"Models for Mercenaries CS" by Gleb Cornery,
"Mercenaries CS" by Gleb Cornery,
"Sailor Cat's Wondrous Goody Huts" by Sailor Cat,
"Sailor Cat's Emergent Goody Huts" by Sailor Cat,
"Customization VI" by Zegangani,
"Let Me Patch That For You" by H.Humpel,
"Plati's City States" by Plati,
"CypRyan's Workable Outer Rings" by CypRyan, TheColdHands and Phantagonist,
"Temudjin's Free City States (v2)" by Temudjin,
"Starting Free Cities [R&F]" by HandyVac,
"Phantagonist’s Slavery and Emancipation" by Phantagonist,
"Slavery" by Ket-Enthusiast,
"False Flag Black Ops" by Gyogen22,
"Barbarians Evolved (Civ 6)" by Charsi,
"Bargain Barbarian Clans" by Sailor Cat,
"Military Tactics" by Angryr,
"Sailor Cat's Watchtower Improvement" by Sailor Cat,
"Mikecro's Military Camp Improvement" by Mikecro,
"Mikecro's Viking Burial Ship Unique Improvement" by Mikecro,
"Rose Garden" by Mikecro, 
"Christmas Tree" by Mikecro,
"Gedemo Dolmen Improvement" by Gedemo,
"Gedemo Racetrack Improvement" by Gedemo,
"指路牌改良设施" by 336tarot,
"Village - Tile Improvement" by digital_mouse,
"Bonus Resource Improvements" by JNR,
"MC's Lefkós Pýrgos (White Tower)" by MC,
"Radiant Additional Helpful Buildings by Shirohô,
"No min distance for Encampment" by NHC,
"Districts Dont Remove Yields" by PhantomJ_M and 榊野木乃实,
"Unique Improvements in Rainforests" by Luke ✞ Jesus Saves ✞,
"Unique Improvements in Forests" by Luke ✞ Jesus Saves ✞,
"Suburban Roads" by JNR,
"City Roads" by AOM,
"Removable Roads" by Zegangani ,
"Removable Districts" by Sparrow,
"Remove Mountain Tunnels" by TearsInRain,
"Better Archaeology Site" by Luke ✞ Jesus Saves ✞,
"Anti-Tourism Policy" by Ivan "Shinji" Karamazov,
"Caravansaries++" by Angryr
"Trader Mercenaries - Protect Traders Policy Card" by Luke ✞ Jesus Saves ✞,
"Loyalty from Great Generals" by JNR,
"Regicide++" by Ket-Enthusiast
"Herdsman" by AOM
"Botanist" by AOM
"Alchemist Unit" by Sailor Cat,
"More Spies" by FearSunn,
"Living Things Grow!" by dreadanddespair,
"Real Meteors" by Spectrum,
"Stone rocks!" by JNR
"Passive Defenses" by Sailor Cat,
"Tile Conquest" by Jack in the box,
"Castles - Better Forts" by JNR,
"Strategic Forts" by TC,
"Supply Logistics" by Angryr,
"Passable mountains + static and moving attrition" by Cromcrom,
"Production From Population" by p0kiehl 
"Many Units Depopulate" by dansal,
"Reasonable number of farms" by hominute,
"Tundra Farms" by gametempest,
"绿洲农田 Farm on Oasis" by Euvit,
"Build On Floodplains" by momo
"Citizens Consume 3 Food" by bene_dictator,
"Collateral Damage" by Sejick,
"Bottlep's Cruel War" by bottlep,
"No more AI city spam" by Mdk25,
"Armies of the AI" by Tiramisu,
"Refugees Mod" by FearSunn,
"SpatialX Civilian Helicopter" by SpatialX and Gleb Cornery,
"Icebreaker" by Gleb Cornery,
"Naval Mine" by Gleb Cornery
"Science From Combat" by FearSunn,
"More Culture" by Burkart,
"Larger Borders (Unlimited)" by dreadanddespair
"Z Special Handicaps - Random Events" by Zur13,
"Nere's Inland Flooding and Climate Change" by Nerevatar,
"Forest on Snow" by Inferno, 
"Desert Woods and Marshes" by Sailor Cat,
"Wetlands" by JNR,
"Savannah" by JNR,
"Jungle Plantations" by p0kiehl,
"Builders can plant jungle" by 336tarot,
"Green Cities - Districts in Forest" by JNR,
"Districts in Rainforests" by Luke ✞ Jesus Saves ✞,
"Fight for Admirals and Generals" by Junky,
"Destroy dams by yourself" by bottlep
"Persuade Defectors Project" by Sailor Cat,
"Latin American Resources" by Leugi & p0kiehl,
"CIVITAS Resources" by Sailor Cat, thecrazyscotsman, SeelingCat, chimp & p0kiehl
"Sukritact's Oceans" by sukritact,
"Sukritact's Resources" by sukritact,
"Resourceful 2" by Amatheria, Zegangani and p0kiehl,
"CIVITAS Resources" by Sailor Cat, thecrazyscotsman, SeelingCat, chimp and p0kiehl,
"Natural Gas" by Searching...
"Cannabis and Hemp" by AOM
"Iron-eating Beast (aka Panda)" by WindFly
"Reindeer" by AOM,
"Resource Cultivation" by Zegangani,
"District-Themed Recruiting" by JNR,
"Terra Mirabilis" by Deliverator23 and chimp
"Mappa Mundi" by SeelingCat, thecrazyscotsman and chimp,
"Better Unit List" by bolbas,
"Better Builder Charges Tracking" by wltk,
"Better Levied Turns Tracking" by jeffrey.vest,
"Z Unit Marks" by Zur13,
"Enhanced Heal Tooltip" by FK1024,
"Z Unit Selection History Navigation" by Zur13,
"Sukritact's More City and Unit Info Stack" by sukritact,
"Sukritact's Simple UI Adjustments" by  by sukritact,
"Toggle UI Banners" by Kornstalx,
"UI Plugins Framework" by FiatAccompli,
"Diplomacy Compatibility Patch" by Adriaman,
"City Banner Compatibility Patch" by Adriaman,
"Population Notification Minimal" by FearSunn
"Religion Notification with Vision" by FearSunn,
"Extended Diplomacy Ribbon" by Aristos,
"Show Food and Production on top panel" by xiaoxiaocat,
"NotificationClear" by 336tarot,
"Enhanced Camera" by DahakaMVl,
"Happiness and Growth Indicators" by lockstep,
"Automated Builders + Archaeologists (2018) [DEPRECATED]" by Kyl
"[UI]Strategy Resources to Production" by Windfly,
"Close Panels" by FK1024,
"Right Click Close Production" by Kornstalx,
"Endgame Map Replay" by Technoluddite 
"Current Time of Day" by donald23
"Stop Moving the Skip Turn Button!" by Technoluddite,
"What Did I Promise?" by Technoluddite
"Sukritact's Global Relations Panel" by sukritact
"Task Force Group Movement" by Gyogen22,
"Spy City Tooltip" by Zur13,
"Tory's MorePromotions" by ToryJang,
"Sailor Cat's Upgrades Keep Unique Abilities" by Sailor Cat,
"Spy Promotion Tree" by Luke ✞ Jesus Saves ✞,
"Aircraft Carriers Perfected" by NullSpace,
"Gift It To Me" by Fampat and NCC1701
"Fast Forward AI Turns" by Zugaikotsu 
"Real Era Stop" by infixo,
"Take your Time Ultimate - Slower Research Trees" by joshmanisdabomb

**Comment by Wild-W** [comment]
Can you elaborate? I'm not sure what you're asking me to do here. To clarify, I am taking requests to patch base game bugs or expose functionality that allows for new things to happen. I'm not bug fixing other people's mods. And if I were, I don't even know what whats wrong with the mods here.

**Comment by Martianganja** [comment]
aye my bad thanks anyway
